# Generated by Django 5.1.6 on 2025-02-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="about",
            new_name="about_me",
        ),
    ]
